version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: todo-mongodb
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - todo-app-network
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: todo-backend
    ports:
      - "5001:5001"
    depends_on:
      - mongodb
    environment:
      - PORT=5001
      - MONGODB_URI=mongodb://mongodb:27017/TODO
      - NODE_ENV=production
    networks:
      - todo-app-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: todo-frontend
    ports:
      - "80:80"
    environment:
      - REACT_APP_API_URL=http://localhost:5001
    depends_on:
      - backend
    networks:
      - todo-app-network
    restart: unless-stopped

networks:
  todo-app-network:
    driver: bridge

volumes:
  mongodb_data:
