apiVersion: v1
kind: Service
metadata:
  name: backend-svc
spec:
  selector:
    app: backend
  type: ClusterIP
  ports:
    - port: 5001
      targetPort: 5001
      name: http
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
spec:
  selector: { app: frontend }
  type: NodePort
  ports: [{ port: 80, targetPort: 80, nodePort: 30001 }]
